### PR TITLE
add github action for release_tooling

### PR DESCRIPTION
**Pull request by jamesgorrie**
quick test

### CODE REVIEW

**Comment by kenoir** [comment]
This repo builds in travis right now, though this mechanism is nicer I think. Ping @alexwlchan for a look. 

Do you think this is worth cleaning up and replacing Travis?

**Comment by alexwlchan** [comment]
No problem with GitHub Actions, but a couple of thoughts on this particular method:

1. You need to build all our images, and Travis does that dynamically – with this approach we’d need to remember to add each image

2. SHA hashes are terrible for ordering. Is 1a26de3 newer than 87a6df1? I prefer the Travis build numbers.

I have been thinking about revamping this, and going in the direction of the CHANGELOG/RELEASE style we use elsewhere – so we can track changes to images more easily. But that works better in Travis, IMO.

**Comment by alexwlchan** [comment]
Of course, GitHub CI makes this more interesting: https://github.blog/2019-08-08-github-actions-now-supports-ci-cd/

**Comment by kenoir** [comment]
💀

**Pull request closed without merging**
